//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SMS.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _24_128 {
            get {
                object obj = ResourceManager.GetObject("24-128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _3badfb6c96f92b6bbcefe3f487f357db {
            get {
                object obj = ResourceManager.GetObject("3badfb6c96f92b6bbcefe3f487f357db", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _51decf5a3f5b86718da705b2a809469f {
            get {
                object obj = ResourceManager.GetObject("51decf5a3f5b86718da705b2a809469f", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _851_128 {
            get {
                object obj = ResourceManager.GetObject("851-128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _Data_Management_128 {
            get {
                object obj = ResourceManager.GetObject("_Data_Management-128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap b16faae3f6e40d9040e1c124d862a2eb {
            get {
                object obj = ResourceManager.GetObject("b16faae3f6e40d9040e1c124d862a2eb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap calendar_128 {
            get {
                object obj = ResourceManager.GetObject("calendar-128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap d7656c4cf1ec9b34bea0fafea62b48bed0cbf641 {
            get {
                object obj = ResourceManager.GetObject("d7656c4cf1ec9b34bea0fafea62b48bed0cbf641", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap depositphotos_43727773_stock_photo_composition_with_glasses_and_books {
            get {
                object obj = ResourceManager.GetObject("depositphotos_43727773-stock-photo-composition-with-glasses-and-books", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap download {
            get {
                object obj = ResourceManager.GetObject("download", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap download__1_ {
            get {
                object obj = ResourceManager.GetObject("download (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap energy {
            get {
                object obj = ResourceManager.GetObject("energy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Formal_meeting_Copy_128 {
            get {
                object obj = ResourceManager.GetObject("Formal_meeting_Copy-128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Grades_In_Rigorous_Courses {
            get {
                object obj = ResourceManager.GetObject("Grades-In-Rigorous-Courses", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Grades_Transcript_Education_Exam_128 {
            get {
                object obj = ResourceManager.GetObject("Grades-Transcript-Education-Exam-128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap if_Exit_132037 {
            get {
                object obj = ResourceManager.GetObject("if_Exit_132037", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap images {
            get {
                object obj = ResourceManager.GetObject("images", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_arabic_alphabet_learning_class_course_arabic_alphabet_cliparts_5aafe2a7e62579_2829841415214762639427 {
            get {
                object obj = ResourceManager.GetObject("kisspng-arabic-alphabet-learning-class-course-arabic-alphabet-cliparts-5aafe2a7e6" +
                        "2579.2829841415214762639427", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_chemistry_chemical_formula_teacher_science_cartoon_chemistry_teacher_5a9479a2162212_3353910415196799060907 {
            get {
                object obj = ResourceManager.GetObject("kisspng-chemistry-chemical-formula-teacher-science-cartoon-chemistry-teacher-5a94" +
                        "79a2162212.3353910415196799060907", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_computer_icons_button_sleep_mode_symbol_on_off_5ac7d87504b2d2_5348980615230465170193 {
            get {
                object obj = ResourceManager.GetObject("kisspng-computer-icons-button-sleep-mode-symbol-on-off-5ac7d87504b2d2.53489806152" +
                        "30465170193", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_computer_icons_login_user_system_administrator_ima_editing_mafsyah_template_5b75843b07ec75_8860585515344282190325 {
            get {
                object obj = ResourceManager.GetObject("kisspng-computer-icons-login-user-system-administrator-ima-editing-mafsyah-templa" +
                        "te-5b75843b07ec75.8860585515344282190325", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_computer_icons_shutdown_button_icon_transparent_shutdown_5ab0c4b236dd68_2558556415215341302247 {
            get {
                object obj = ResourceManager.GetObject("kisspng-computer-icons-shutdown-button-icon-transparent-shutdown-5ab0c4b236dd68.2" +
                        "558556415215341302247", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_family_silhouette_father_parents_5ac75b450c9873_8758492015230144690516 {
            get {
                object obj = ResourceManager.GetObject("kisspng-family-silhouette-father-parents-5ac75b450c9873.8758492015230144690516", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_flag_of_germany_map_flag_of_austria_germany_5ad82e2d51f152_6943555115241170373357 {
            get {
                object obj = ResourceManager.GetObject("kisspng-flag-of-germany-map-flag-of-austria-germany-5ad82e2d51f152.69435551152411" +
                        "70373357", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_flag_of_spain_map_english_spain_flag_vector_icon_5abb04c82031a0_1994794715222058961319 {
            get {
                object obj = ResourceManager.GetObject("kisspng-flag-of-spain-map-english-spain-flag-vector-icon-5abb04c82031a0.199479471" +
                        "5222058961319", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_lettering_alphabet_cursive_font_alphabets_5ac98749a6c862_3892344615231568096832 {
            get {
                object obj = ResourceManager.GetObject("kisspng-lettering-alphabet-cursive-font-alphabets-5ac98749a6c862.3892344615231568" +
                        "096832", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_mathematics_subtraction_addition_operation_mathema_maths_5b0faa4be4df23_1836823815277532919375__1_ {
            get {
                object obj = ResourceManager.GetObject("kisspng-mathematics-subtraction-addition-operation-mathema-maths-5b0faa4be4df23.1" +
                        "836823815277532919375 (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_professor_teacher_student_clip_art_cartoon_bald_old_man_professor_teacher_5a84e1651eaf61_4488191115186578931257 {
            get {
                object obj = ResourceManager.GetObject("kisspng-professor-teacher-student-clip-art-cartoon-bald-old-man-professor-teacher" +
                        "-5a84e1651eaf61.4488191115186578931257", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_schoolyard_drawing_cartoon_school_building_material_png_5a95d904d800f3_7046775115197698608848__1_ {
            get {
                object obj = ResourceManager.GetObject("kisspng-schoolyard-drawing-cartoon-school-building-material-png-5a95d904d800f3.70" +
                        "46775115197698608848 (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_student_learning_education_vector_students_5a6c15371b3d71_8537361215170327591116 {
            get {
                object obj = ResourceManager.GetObject("kisspng-student-learning-education-vector-students-5a6c15371b3d71.853736121517032" +
                        "7591116", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_symbol_science_atom_chemistry_clip_art_png_free_atom_download_images_5abb014abc5fd1_7376547215222050027716 {
            get {
                object obj = ResourceManager.GetObject("kisspng-symbol-science-atom-chemistry-clip-art-png-free-atom-download-images-5abb" +
                        "014abc5fd1.7376547215222050027716", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_thutmose_amarna_nefertiti_bust_ancient_egypt_faiyu_tupac_5ac58ae2a2ce43_9714283115228955866669 {
            get {
                object obj = ResourceManager.GetObject("kisspng-thutmose-amarna-nefertiti-bust-ancient-egypt-faiyu-tupac-5ac58ae2a2ce43.9" +
                        "714283115228955866669", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_world_map_english_language_vector_world_geography_map_5a68dcb358df32_777637161516821683364 {
            get {
                object obj = ResourceManager.GetObject("kisspng-world-map-english-language-vector-world-geography-map-5a68dcb358df32.7776" +
                        "37161516821683364", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap on_time__128 {
            get {
                object obj = ResourceManager.GetObject("on_time_-128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Project_management_Product_Status_Account_128 {
            get {
                object obj = ResourceManager.GetObject("Project_management_Product_Status_Account-128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap select_all_128 {
            get {
                object obj = ResourceManager.GetObject("select_all-128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap student_7_128 {
            get {
                object obj = ResourceManager.GetObject("student-7-128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap teachers_thumbs_up {
            get {
                object obj = ResourceManager.GetObject("teachers-thumbs-up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Technology_Mix___Final_22_128 {
            get {
                object obj = ResourceManager.GetObject("Technology_Mix_-_Final-22-128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap title_bar {
            get {
                object obj = ResourceManager.GetObject("title_bar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tuition_centre_private_tutor_2 {
            get {
                object obj = ResourceManager.GetObject("tuition-centre-private-tutor-2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap user {
            get {
                object obj = ResourceManager.GetObject("user", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
